### ISSUE TITLE
setUp and tearDown undefined

### ISSUE THREAD

**Issue by teemal** [ThrowTheSwitch/Unity#433]
Just pulled the source a few minutes ago. Ran the example test code off your guys main website but couldn't get gcc to compile it due to an undefined reference to setUp and tearDown inside UnityDefaultTestRun. Searched for them but couldn't find any definitions for the functions. Commented them out and things seem to run fine, but I'm assuming they have some importance.

**Comment by Xenoamor** [comment]
I'm also seeing this, I'll have a look and see what's going on

**Comment by Xenoamor** [comment]
Okay this is a regression caused by https://github.com/ThrowTheSwitch/Unity/commit/0000f1e6d2607d8e081be2f96440e22dd81bfb38. https://github.com/ThrowTheSwitch/Unity/commit/a2f25d05d893f5644f14715222e927aa2e8773cf works as expected

**Comment by mvandervoord** [comment]
Are you sure? 0000f1E seems to only add functionality and not change that behavior?

**Comment by Xenoamor** [comment]
My mistake! It's this one https://github.com/ThrowTheSwitch/Unity/commit/45020b0d3b03f0313a25ebbc15107de39bb901da

Inserting `#define UNITY_INCLUDE_SETUP_STUBS` into line 7 of unity.c resolves this issue for me

**Comment by Xenoamor** [comment]
Adding `-DUNITY_INCLUDE_SETUP_STUBS` to my build tools works. I'm not sure if this will effect other people using CMock but not Unity. I imagine this isn't an issue if you use CMock with Unity

**Comment by teemal** [comment]
Sorry for the (long) delay. I'm just now getting back to this. Using gcc, I figured it out. It was a pound define and ifdef issue, but I had to declare `#define UNITY_INCLUDE_SETUP_STUBS` near the top of unity.h
